### ISSUE TITLE
Ejects CD after failed MusicBrainz lookup

### ISSUE THREAD

**Issue by broonie** [thomasvs/morituri#131] opened 2015-07-20 10:39 UTC
Whenever a MusicBrainz lookup fails morituri ejects the CD. This has never been behavior I've found at all helpful - usually what I then do is enter the CD information into MusicBrainz based on the packaging and retry the rip (it is possible that the only information might be on the CD but it's not going to be the common case). It would be much better to just leave the CD in the drive to facilitate this workflow.

**Comment by thomasvs** [comment] 2015-07-20 12:50
morituri ejects when it's done and the human in front of the computer should do something about it.  That something is either put in a new CD and start again, or take action on whatever failed.  It's consistent and helpful.

You don't say why it would be much better to just leave the CD in.  Especially given that morituri closes the disc tray when you start a rip (unless if you're on a laptop, which doesn't support that, but if you're stuck with a laptop drive you have bigger issues to worry about), I don't see why leaving it in is better.

**Comment by broonie** [comment] 2015-07-20 14:23
The most obvious thing the user would want to do in response to this is to follow the link provided and then retry the rip like I said, ejecting the CD doesn't help with that and as you say not all drive enclosures will close by themelves. I have noticed that if the rip fails for some reason later on (eg, a dirty CD) then the CD is /not/ ejected so we definitely don't have consistency here.

It's also quite unhelpful when you start a rip, walk away from the computer and then come back with the screen blanked - it's easy to assume that the rip has completed and put the CD away before discovering that the rip actually failed and you need to get the CD again. This happens to me moderately often and is the main source of annoyance here.

**Comment by thomasvs** [comment] 2015-08-03 02:16
I just ripped three cd's.  I put them in and start it.  It takes a while before it can actually know that it's not in musicbrainz, so I walk away from my computer and continue cooking.  The CD ejecting in two out of three cases was the helpful sign that I should get back to my computer and do something about the CD not being in musicbrainz.  This is how it was intended, and today's experience confirms that it makes sense to me, so this behaviour is not going to change.

I suggest you don't assume that the rip is completed.  Since, to start the next rip, you need to actually unblank the screen anyway, you just have to order from remove-cd-then-unblank-and-rip-again to unblank-check-if-rip-worked-remove-cd-rip-again.

As for the error case not ejecting, I agree that is inconsistent and simply should be fixed.  Please let me know what error case triggered this and file a separate issue for it so we can fix it.

Thanks
Thomas

**Closed by thomasvs** 2015-08-03 02:16 UTC

**Comment by broonie** [comment] 2015-08-13 09:25
I'm very rarely doing bulk ripping of things so it's more likely to be the case that I'm just going to put the CD away and go off and do other things 

Errors with not ejecting seem to happen it at least all cases where the rip fails to parse the CD TOC (which are the majority of fatal errors I see) and IIRC also in cases where the physical read of audio from the disc fails though I don't have any CDs to hand exhibiting such behavior.

Please at least consider making this behavior configurable.
